version: 2

jobs:
  test-python37:
    docker:
      - image: python:3.7-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-py37-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            ~/.local/bin/pipenv install --python python3.7 --dev
      - save_cache:
          key: deps-py37-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/"
      - run: ~/.local/bin/pipenv run tox -e clean,py37,report

  test-python36:
    docker:
      - image: python:3.6-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-py36-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            ~/.local/bin/pipenv install --python python3.6 --dev
      - save_cache:
          key: deps-py36-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/"
      - run: ~/.local/bin/pipenv run tox -e clean,py36,report

  test-python35:
    docker:
      - image: python:3.5-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-py35-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            ~/.local/bin/pipenv install --python python3.5 --dev
      - save_cache:
          key: deps-py35-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/"
      - run: ~/.local/bin/pipenv run tox -e clean,py35,report

  check:
    docker:
      - image: python:3.7-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-check-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            ~/.local/bin/pipenv install --python python3.7 --dev
      - save_cache:
          key: deps-check-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/"
      - run: ~/.local/bin/pipenv run tox -e check

  deploy:
    docker:
      - image: python:3.7-stretch
        environment:
          PIPENV_VENV_IN_PROJECT: true
    working_directory: ~/circleci
    steps:
      - checkout
      - restore_cache:
          key: deps-deploy-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            ~/.local/bin/pipenv install --python python3.7 --dev
      - save_cache:
          key: deps-deploy-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/"
      - run:
          command: |
            pipenv run python setup.py sdist bdist_wheel
            pipenv run twine upload dist/*

workflows:
  version: 2
  build:
    jobs:
      - test-python37
      - test-python36
      - test-python35
      - check
      - deploy:
          context: PyPI Deploy
          requires:
            - test-python37
            - test-python36
            - test-python35
            - check
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
