version: 2

jobs:
  build:
    working_directory: ~/circleci
    docker: # run the steps with Docker
      - image: circleci/python:3.7-stretch
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
    steps: # steps that comprise the `build` job
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |
            pip install --user pipenv
            pipenv install --dev
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ".venv"
            - "~/.local/lib/"
      - run:
          command: tox
